### ISSUE TITLE
Release on crates.io

### ISSUE THREAD

**Issue by silwol** [forrest-marshall/serde-hex#1]
This library looks like well-crafted and well-documented code, and would be of good use for me (and probably others). It looks more complete than the hex-serde crate which is already available on crates.io.  I would really like to see serde-hex published to crates.io.

**Comment by InsidiousMind** [comment]
Absolutely! I'm happy after stumbling upon this Github repo. the current hex-serde crate on crates.io can't handle '0x'. I was about to implement `deserialize` myself before finding this.

**Comment by mike7b4** [comment]
Agree this should be on crates.io. I know there already is a hex-serde  so maybe a name conflict? But maybe you can rename it serde-hexify or something else....

**Comment by elpiel** [comment]
@forrest-marshall any updates on this?

**Comment by forrest-marshall** [comment]
Sorry for the delay.  Apparently I deactivated notifications at some point.  Fixed.
I think this crate could use some serious pruning and simplification, but I'm happy to publish the current state for those who find it useful.  I'll do some basic cleanup tonight & get it published.

**Comment by forrest-marshall** [comment]
Alright, its [published](https://crates.io/crates/serde-hex).  Version `0.1` conforms to the pre-publish API.

**Comment by silwol** [comment]
Thanks a lot, that's great!
