### ISSUE TITLE
A way to manually get the serialized value(String)

### ISSUE THREAD

**Issue by elpiel** [forrest-marshall/serde-hex#3]
I've started using the `serde(with="..")` to serialize to a `StrictPfx`, but since for simplifications we wanted to use the hex value as a string and save it in the Database, I had to use another library and manually prefix the hex value (i.e. doing the same thing that the serializer is doing).

I was wondering if it's possible to have that option and be able to get the string value?

Not sure what you meant with https://github.com/forrest-marshall/serde-hex/issues#issuecomment-497450005 , but also I can give a hand and help with the implementation.

**Comment by forrest-marshall** [comment]
If I understand correctly, you want to be able to bypass `serde` and write the configured hex representation directly to a string, yeah?  If so, the provided [`into_hex`](https://docs.rs/serde-hex/0.1.0/serde_hex/trait.SerHex.html#method.into_hex) method should do the trick:

```rust
let bytes: [u8;4] = [0xde,0xad,0xbe,0xef];
let hex = SerHex::<StrictPfx>::into_hex(&bytes).unwrap();
assert_eq!(hex,"0xdeadbeef");
```
The `into_hex` and `serialize` methods both just call [`into_hex_raw`](https://docs.rs/serde-hex/0.1.0/serde_hex/trait.SerHex.html#tymethod.into_hex_raw) which works with anything that implements `io::Write`.

Regarding my comments on "pruning and simplification", I'd like to figure out a way to get rid of the `SerHexOpt` and `SerHexSeq` traits if possible (haven't given this much thought yet, might not be possible without [specialization](https://github.com/rust-lang/rust/issues/31844)).  Some of the currently exported macros are pretty unnecessary as well.  I'm always open to suggestions and contributions, but these are just nitpicks really.

**Comment by elpiel** [comment]
That's what I needed! Thank you! Somehow I've missed it.
